version: '3.8'

services:
  # Neon Local proxy for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local-dev
    ports:
      - '5432:5432'
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      PARENT_BRANCH_ID: ${PARENT_BRANCH_ID:-main}  # Creates ephemeral branches
      DELETE_BRANCH: ${DELETE_BRANCH:-true}  # Auto-cleanup when container stops
    volumes:
      # Optional: Persist branch per Git branch
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URL: postgres://neon:npg@neon-local:5432/neondb
      ARCJET_KEY: ${ARCJET_KEY}
    volumes:
      # Mount source code for hot-reloading in development
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
